### ISSUE TITLE
User script not triggering on 'Create Page`

### ISSUE THREAD

**Issue by djonsson** [ilons/tampermonkey-confluence-edit-fix#2]
**Steps to reproduce**
1. Enter any space
2. Click "Create Page"
3. Notice that the user script is not triggering.

**Comment by ilons** [comment]
Thank you, this is fixed in commit [58808ec7e2e6863fad5bb9b780153caa7d125ab4](https://github.com/ilons/tampermonkey-confluence-edit-fix/commit/58808ec7e2e6863fad5bb9b780153caa7d125ab4)
